### ISSUE TITLE
New methods, modules roadmap

### ISSUE THREAD

**Issue by MajorLift** [poteat/hkt-toolbelt#20]
These are some features I'd like to potentially work on adding to the library.
- This list is neither exhaustive nor definitive. It's only intended as a starting point for discussion.

## TODO

- Utilities

    - [ ] `Opaque` - Create an opaque type.
    - [ ] `UnwrapOpaque` - Revert an opaque type back to its original type.
    - [ ] `InvariantOf` - Create an invariant type, which is a type that does not accept supertypes and subtypes.
    - [ ] `LiteralToPrimitive` - Convert a literal type to the primitive type it belongs to.
    - [x] `UnionToIntersection` - Convert a union type to an intersection type.
    - [x] `UnionFromList` - Convert a list type into a union type.

- Kind
    - [x] `Unapply`

- List
    - [ ] `FixedLengthArray` - Create a type that represents an array of the given type and length.
    - [ ] `MultidimensionalArray` - Create a type that represents a multidimensional array of the given type and dimensions.
    - [x] `At`
    - [x] `Accumulate`
    - [x] `Iterate`
    - [x] `Zip`
    - [x] `Range<START, STOP, STEP>`

- Conditional
    - [x] `EqualsAll` - Check whether all elements of a list are the same.
    - [x] `ExtendsAll` - Check whether all elements of a list extend an input type.
    - [ ] `Match` - Pattern matching.

- New number modules

    - [ ] `Integer`
    - [ ] `Decimal`
    - [ ] `DecimalDigitList`
    - [ ] `Fractional`

- Arithmetic methods for `Number`, `Integer`, `DecimalDigitList`, `Decimal`

    - [ ] `IsNegative`
    - [ ] `IsNonNegative`
    - [ ] `IsPositive`
    - [ ] `Greater`
    - [ ] `GreaterEq`
    - [ ] `Lesser`
    - [ ] `LesserEq`
    - [ ] `Add`
    - [ ] `Subtract`
    - [ ] `SubtractBy`
    - [ ] `Multiply`
    - [ ] `Divide`
    - [ ] `DivideBy`
    - [ ] `Modulo`
    - [ ] `ModuloBy`
    - [ ] `Floor`
    - [ ] `Ceiling`
    - [ ] `Min`
    - [ ] `Max`

- Object
    - [ ] `Exact` - Create a type that does not allow extra properties.
    - [x] `ValueOf` - Create a union of the given object's values, and optionally specify which keys to get the values from.
    - [x] `MergeDeep` - Merge two objects or two arrays/tuples recursively into a new type.
    - [ ] `OptionalKeysOf` - Extract all optional keys from the given type.
    - [ ] `RequiredKeysOf` - Extract all required keys from the given type.
    - [ ] `SetOptional` - Create a type that makes the given keys optional.
    - [ ] `SetRequired` - Create a type that makes the given keys required.
    - [ ] `SetWritable` - Create a type that requires at least one of the given keys.
    - [ ] `SetNonNullable` - Create a type that makes the given keys non-nullable.

- Class
    - [ ] `Class`
    - [ ] `Constructor`
    - [ ] `AbstractClass`
    - [ ] `AbstractConstructor`
    - [ ] `SerializeClass`
    - [ ] `DeserializeClass`

- Change case

    - [ ] `CamelCase` - Convert a string literal to camel-case (fooBar).
    - [ ] `CamelCasedProperties` - Convert object properties to camel-case (fooBar).
    - [ ] `CamelCasedPropertiesDeep` - Convert object properties to camel-case recursively (fooBar).
    - [ ] `KebabCase` - Convert a string literal to kebab-case (foo-bar).
    - [ ] `KebabCasedProperties` - Convert a object properties to kebab-case recursively (foo-bar).
    - [ ] `KebabCasedPropertiesDeep` - Convert object properties to kebab-case (foo-bar).
    - [ ] `PascalCase` - Converts a string literal to pascal-case (FooBar)
    - [ ] `PascalCasedProperties` - Converts object properties to pascal-case (FooBar)
    - [ ] `PascalCasedPropertiesDeep` - Converts object properties to pascal-case (FooBar)
    - [ ] `SnakeCase` - Convert a string literal to snake-case (foo_bar).
    - [ ] `SnakeCasedProperties` - Convert object properties to snake-case (foo_bar).
    - [ ] `SnakeCasedPropertiesDeep` - Convert object properties to snake-case recursively (foo_bar).
    - [ ] `ScreamingSnakeCase` - Convert a string literal to screaming-snake-case (FOO_BAR).
    - [ ] `DelimiterCase` - Convert a string literal to a custom string delimiter casing.
    - [ ] `DelimiterCasedProperties` - Convert object properties to a custom string delimiter casing.
    - [ ] `DelimiterCasedPropertiesDeep` - Convert object properties to a custom string delimiter casing recursively.

- Validators

    - [ ] `Pattern<T extends RegExp>`
    - [ ] `IsAlpha`
    - [ ] `IsAlphaNumeric`
    - [ ] `LengthInRange`
    - [ ] `Includes`
    - [ ] `Excludes`

**Comment by poteat** [comment]
On a branch I'm working on I have a `NaturalNumber.IsLessThan` utility, so I went ahead and checked one off 👍

**Comment by MajorLift** [comment]
Superseded by #52
