### ISSUE TITLE
Official launch of documentation site

### ISSUE THREAD

**Issue by MajorLift** [poteat/hkt-toolbelt#76]
## Explanation

We're in the process of launching an official documentation site that will provide user-friendly information about our library API, and will automatically keep up-to-date with the contents of the JSDoc comments in our codebase. 

(Example live site deployed from fork: https://majorlift.github.io/hkt-toolbelt/)

The following are the remaining tasks in that process:

## Deployment

- [x] https://github.com/poteat/hkt-toolbelt/pull/68
  - [ ] Configure GitHub Pages to deploy from `gh-pages`
  - [ ] Configure official documentation URL:
    a) Use `poteat.github.io/hkt-toolbelt` (conflict with `code.lol`?)
    b) Transfer repo into hkt-toolbelt organization and use `hkt-toolbelt.github.io`
    c) Purchase new domain
  - [ ] Add documentation link to repo "About" section
- [ ] https://github.com/poteat/hkt-toolbelt/pull/66
  - [ ] Update links in PR to official URL
- [ ] Announcements

## Contents

- [ ] https://github.com/poteat/hkt-toolbelt/issues/69
- [ ] https://github.com/poteat/hkt-toolbelt/issues/70

## References

- Closes https://github.com/poteat/hkt-toolbelt/issues/63
- Closes https://github.com/poteat/hkt-toolbelt/issues/18

**Comment by MajorLift** [comment]
@poteat Is there anything blocking the documentation site from being launched? We're currently publishing the GitHub Pages to the `gh-pages` branch with the "Publish docs to GitHub Pages" action, but it seems like the docs aren't being deployed to a public website from there.

These are the steps to deploy:
1. Navigate to "Settings - Pages - Build and Deployment"
2. Configure the following:
Source - "Deploy from a branch"
Branch - "gh-pages", "/(root)"

![image](https://github.com/poteat/hkt-toolbelt/assets/34228073/9f2d54eb-15fc-4a84-95fa-60a9dd2938b5)

I think even with incomplete coverage, an up-to-date docs website would be less confusing for new users than the outdated API docs we currently have in the readme.

**Comment by MajorLift** [comment]
Closed by #66
